name: Generate Docs
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      
      - name: Build and Generate Docs
        run: |
          dotnet build
          mkdir -p docs
          
          # Convert XML to HTML
          echo "<!DOCTYPE html><html><head><title>BankingApp Docs</title><style>body{font-family:sans-serif;margin:2em}</style></head><body><h1>BankingApp Documentation</h1>" > docs/index.html
          
          # Process XML comments
          xmlstarlet sel -t -m "//member[starts-with(@name,'T:')]" -v "concat('&lt;h2&gt;', substring-after(@name,'T:'), '&lt;/h2&gt;&lt;p&gt;', summary, '&lt;/p&gt;')" -n "bin/Debug/net9.0/BankingApp.xml" >> docs/index.html
          
          echo "</body></html>" >> docs/index.html
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs